services:
  postgres:
    image: postgres
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  bot:
    build: .
    container_name: bot-container
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
    restart: always
    entrypoint: /bin/bash -c "./wait-for-it.sh postgres:5432 -- python main.py"


volumes:
  postgres_data:

