services:
  postgres:
    image: postgres
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

#  bot:
#    build: .
#    container_name: bot-container
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    environment:
#      POSTGRES_HOST: postgres  # Имя сервиса PostgreSQL
#      POSTGRES_PORT: ${DB_PORT}
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    restart: always
#    entrypoint: /bin/bash -c "rm -rf /root/.cache/* && exec python main.py"

volumes:
  postgres_data:








